### ISSUE TITLE
How to restore the toolbar of Mac version Veloview?

### ISSUE THREAD

**Issue by mjw06** [Kitware/VeloView#53]
I closed the toolbar by accident on my Mac version VeloView. I know it is easy to restore it on Win version VeloView but not for Mac version. Do anyone know how to restore the toolbar.  Many thanks in advance.

**Comment by bastienjacquet** [comment]
Hello,
I am answering here too, since it could help other people.

You should be able to get one toolbar back by doing the following:
press [F8] (or "Tool">"Python Console")
Then type the following:
vv.app.geolocationToolBar.visible=1

From there, you can right clic to show the other toolbars.
Best regard,
Bastien Jacquet, VeloView Lead Developer
